language: node_js
node_js:
  - "node"
  
sudo: false

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

before_install:
  - rvm install 2.3.3

install:
   - npm i -g eslint
   - bundle install

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master    # test master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
